<a href="https://colab.research.google.com/github/Nada-Naveesh/Machine_Learning/blob/main/L1%26L2regular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
# Suppress Warnings for clean notebook
import warnings
warnings.filterwarnings('ignore')

In [3]:
# read dataset
dataset = pd.read_csv('ml_borne.csv')

In [4]:
dataset.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3.0,h,1490000.0,S,Jellis,1/04/2017,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3.0,h,1220000.0,S,Marshall,1/04/2017,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3.0,h,1420000.0,S,Nelson,1/04/2017,3067.0,Northern Metropolitan,4019.0,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3.0,h,1515000.0,S,Barry,1/04/2017,3040.0,Western Metropolitan,1543.0,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2.0,h,670000.0,S,Nelson,1/04/2017,3042.0,Western Metropolitan,3464.0,10.4,Moonee Valley City Council

In [6]:
# let's use limited columns which makes more sense for serving our purpose
cols_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount',
               'Distance', 'CouncilArea', 'Price']
dataset = dataset[cols_to_use]

In [7]:
dataset.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Price
0,Abbotsford,3.0,h,S,Jellis,Northern Metropolitan,4019.0,3.0,Yarra City Council,1490000.0
1,Abbotsford,3.0,h,S,Marshall,Northern Metropolitan,4019.0,3.0,Yarra City Council,1220000.0
2,Abbotsford,3.0,h,S,Nelson,Northern Metropolitan,4019.0,3.0,Yarra City Council,1420000.0
3,Aberfeldie,3.0,h,S,Barry,Western Metropolitan,1543.0,7.5,Moonee Valley City Council,1515000.0
4,Airport West,2.0,h,S,Nelson,Western Metropolitan,3464.0,10.4,Moonee Valley City Council,670000.0

In [8]:
dataset.shape

(54371, 10)

In [9]:
dataset.isna().sum()

Suburb               0
Rooms                1
Type                 1
Method               1
SellerG              1
Regionname           1
Propertycount        1
Distance             1
CouncilArea          1
Price            12638
dtype: int64

In [12]:
# Handling Missing values
# Some feature's missing values can be treated as zero (another class for NA values or absence of that feature)
# like 0 for Propertycount, Bedroom2 will refer to other class of NA values
# like 0 for Car feature will mean that there's no car parking feature with house

cols_to_fill_zero = ['Propertycount', 'Distance']
dataset[cols_to_fill_zero] = dataset[cols_to_fill_zero].fillna(0)

# other continuous features can be imputed with mean for faster results since our focus is on Reducing overfitting
# using Lasso and Ridge Regression
# dataset['Landsize'] = dataset['Landsize'].fillna(dataset.Landsize.mean())
# dataset['BuildingArea'] = dataset['BuildingArea'].fillna(dataset.BuildingArea.mean())

In [13]:
#Drop NA values of Price, since it's our predictive variable we won't impute it

dataset.dropna(inplace=True)
dataset.shape

(41733, 10)

In [14]:
#Let's one hot encode the categorical features

dataset = pd.get_dummies(dataset, drop_first=True)
dataset.head()

,Rooms,Propertycount,Distance,Price,Suburb_Aberfeldie,Suburb_Airport West,Suburb_Albanvale,Suburb_Albert Park,Suburb_Albion,Suburb_Alphington,...,CouncilArea_Moreland City Council,CouncilArea_Murrindindi Shire Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,3.0,4019.0,3.0,1490000.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,3.0,4019.0,3.0,1220000.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,3.0,4019.0,3.0,1420000.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,3.0,1543.0,7.5,1515000.0,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2.0,3464.0,10.4,670000.0,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
#Let's bifurcate our dataset into train and test dataset

X = dataset.drop('Price', axis=1)
y = dataset['Price']
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=2)

In [16]:
#Let's train our Linear Regression Model on training dataset and check the accuracy on test set

from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(train_X, train_y)
reg.score(test_X, test_y)

0.660221442166932

In [17]:
reg.score(train_X, train_y)

0.6721027368623163

In [21]:
#Normal Regression is clearly overfitting the data, let's try other models
#Using Lasso (L1 Regularized) Regression Model

from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg.fit(train_X, train_y)
lasso_reg.score(test_X, test_y)

0.6608844275873593

In [23]:
lasso_reg.score(train_X, train_y)

0.6675183722583915

In [24]:
#Using Ridge (L2 Regularized) Regression Model

from sklearn.linear_model import Ridge
ridge_reg= Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(train_X, train_y)
Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.score(test_X, test_y)

0.6557661743444064

In [25]:
ridge_reg.score(train_X, train_y)

0.6577123509590574

In [ ]:
#We see that Lasso and Ridge Regularizations prove to be beneficial when our Simple Linear Regression Model overfits.
#These results may not be that contrast but significant in most cases.
#Also that L1 & L2 Regularizations are used in Neural Networks too

#Ridge: reduces coefficient magnitude → prevents overfitting
#Lasso: reduces coefficient magnitude + performs feature selection → prevents overfitting and simplifies model